title: Startup Weekend Žilina
description: Startup Weekend Žilina. A 54-hour hackathon for people who want to build, learn and pitch.
activeYear: 2026
partnerFormUrl: https://docs.google.com/forms/d/e/1FAIpQLSegoeznHg89Lp7US8lx1hByZuF83Lmw4WQZWDiQoAw_CzKqqg/viewform
